repos:
  - repo: local
    hooks:
    -   id: flake8
        name: Flake8
        description: This hook runs flake8 within our project's poetry environment.
        entry: poetry run flake8
        language: python
        types: [python]
        require_serial: true
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
    -   id: python-check-blanket-noqa
